language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npx jest
  - unset CI

after_script: # Upload coverage reports 
  - COVERALLS_REPO_TOKEN=$coveralls_token 
  - npx jest --coverage
