language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test
  - unset CI
  - npm run build

after_script: # Upload coverage reports 
  - COVERALLS_REPO_TOKEN=$coveralls_token 
  - npm run coveralls
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $githubtoken
  local_dir: build
  on:
    branch: development