language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run test 
  - unset CI

after_success:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token 
  - npm run coveralls
  - npm run build

