apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/mirr254/bright-events-reactjs:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/mirr254/bright-events-reactjs:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: bright-events-reactjs
        chartPath: charts/bright-events-reactjs
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/mirr254/bright-events-reactjs"
          image.tag: "{{.TAG}}"
